# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95ab60ee087f8e6c5c3f4eb6700e3667cb3964410ee025b981c92c28be967344e5708d73bb708166bb94306f58b1e7d1b7f61541bef1460231214a065527aa16

test:
  secret_key_base: df2e05acacc0227b6edb1914bc6bf9d468737435e37e39569cd709d09f0cba3ea226118883d8e418e5737b4a38ee562c53e5ff8453ee808506b65b5273ab8649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
